name: actions-docker-gcr/pull
description: Pull a docker image
author: bappr
branding:
  icon: anchor
  color: blue
inputs:
  registry:      
    description: The registry to get the image from. Defaults to gcr.io
    required: false
  image:
    description: The name of image to get. Defaults to repository name
    required: false
  tag:
    description: The tag of the image. Defaults to the commit SHA
    required: false
  gcloud_key:
    description: A GCloud service account json key, base64 encoded. Should be stored in a secret!
    required: true

runs: 
  using: 'docker'
  image: 'Dockerfile'