name: actions-docker-gcr/sentry
description: Create a release and push the sourcemap to sentry 
author: nandiheath
branding:
  icon: anchor
  color: blue
inputs:
  registry:      
    description: The registry to get the image from. Defaults to gcr.io
    required: false
  image:
    description: The name of image to get. Defaults to repository name
    required: false
  tag:
    description: The tag of the image. Defaults to the commit SHA
    required: false
  sentry_token:
    description: The tag of the image. Defaults to the commit SHA
    required: false
  sentry_org:
    description: The organization on sentry
    required: true
  sentry_project:
    description: The project name on sentry
    required: true
  gcloud_key:
    description: A GCloud service account json key, base64 encoded. Should be stored in a secret!
    required: true

runs: 
  using: 'docker'
  image: 'Dockerfile'