name: actions-docker-gcr/push
description: Push a docker image
author: benjlevesque
branding:
  icon: anchor
  color: blue
inputs:
  registry:      
    description: The registry of the existing image. Defaults to gcr.io
    required: false
  new_registry:
    description: The registry to upload to. Defaults to gcr.io
    required: false
  image:
    description: The name of image to build. Defaults to repository name
    required: false
  tag:
    description: The tag of the image. Defaults to the commit SHA
    required: false
  latest:
    description: If true, will also add latest tag
    required: true
    default: "true"
  gcloud_key:
    description: A GCloud service account json key, base64 encoded. Should be stored in a secret!
    required: true

runs: 
  using: 'docker'
  image: 'Dockerfile'